/** Dated PrizePicks CFB reboot name snapshot 2026-08-27. Not a player_id map. */
export const CFB_OFFICIAL_NAMES = new Set(
  [
    "Mario Craver",
    "Malachi Toney",
    "Dante Moore",
    "CJ Carr",
    "Jayden Maiava",
    "Julian Sayin",
    "Trinidad Chambliss",
    "John Mateer",
    "Jeremiah Smith",
    "Cam Coleman",
    "Bear Bachmeier",
    "Isaiah Sategna",
    "Duce Robinson",
    "Cameron Dickey",
    "Ryan Williams",
    "Dakorien Moore",
    "Marcel Reed",
    "Desean Bishop",
    "Nate Frazier",
    "Charlie Becker",
    "Gunner Stockton",
    "Jaron-Keawe Sagapolutele",
    "Terrance Carter",
    "Darian Mensah",
    "Jordan Faison",
    "Bryant Wesco",
    "Sam Leavitt",
    "Josh Hoover",
    "Trey'Dez Green",
    "Nick Marsh",
    "LaNorris Sellers",
    "LJ Martin",
    "Mason Heintschel",
    "Ryan Wingo",
    "Bryce Underwood",
    "Kewan Lacy",
    "Rocco Becht",
    "Arch Manning",
    "TJ Moore",
    "Mark Fletcher",
    "Antwan Raymond",
    "Cam Cook",
    "Byrum Brown",
    "Jadan Baugh",
  ].map((n) => n.toLowerCase()),
);
