import type { BoardRow, Modifier, Side } from "./types.ts";

function r(
  projectionId: string,
  sportFamily: string,
  league: string,
  eventId: string,
  eventLabel: string,
  playerId: string,
  playerName: string,
  team: string,
  opponent: string,
  market: string,
  marketLabel: string,
  line: number,
  side: Side,
  modifier: Modifier,
  role: string,
  extra: Partial<BoardRow> = {},
): BoardRow {
  return {
    projectionId,
    sportFamily,
    league,
    eventId,
    eventLabel,
    playerId,
    playerName,
    teamId: team,
    team,
    opponent,
    market,
    marketLabel,
    line,
    side,
    offeredHigher: side === "MORE" || extra.offeredHigher === true,
    offeredLower: side === "LESS" || extra.offeredLower === true,
    modifier,
    boardId: extra.boardId ?? "FULL_GAME",
    productType: "PLAYER_PICKS",
    role,
    ...extra,
  };
}

/** Sanitized synthetic PrizePicks-like board. Not a live capture. */
export const DEMO_BOARD: BoardRow[] = [
  r("n1", "basketball", "NBA", "NBA_BOS_NYK", "BOS @ NYK", "TATUM", "Jayson Tatum", "BOS", "NYK", "pts", "Points", 27.5, "MORE", "STANDARD", "F", { offeredLower: true }),
  r("n2", "basketball", "NBA", "NBA_BOS_NYK", "BOS @ NYK", "TATUM", "Jayson Tatum", "BOS", "NYK", "reb", "Rebounds", 8.5, "LESS", "STANDARD", "F", { offeredHigher: true }),
  r("n3", "basketball", "NBA", "NBA_BOS_NYK", "BOS @ NYK", "TATUM", "Jayson Tatum", "BOS", "NYK", "pra", "Pts+Reb+Ast", 38.5, "MORE", "DEMON", "F"),
  r("n4", "basketball", "NBA", "NBA_BOS_NYK", "BOS @ NYK", "BRUNSON", "Jalen Brunson", "NYK", "BOS", "pts", "Points", 28.5, "LESS", "STANDARD", "G", { offeredHigher: true }),
  r("n5", "basketball", "NBA", "NBA_BOS_NYK", "BOS @ NYK", "BRUNSON", "Jalen Brunson", "NYK", "BOS", "ast", "Assists", 6.5, "MORE", "STANDARD", "G", { offeredLower: true }),
  r("n6", "basketball", "NBA", "NBA_BOS_NYK", "BOS @ NYK", "HOLIDAY", "Jrue Holiday", "BOS", "NYK", "pts", "Points", 12.5, "MORE", "GOBLIN", "G"),
  r("n7", "basketball", "NBA", "NBA_LAL_DEN", "LAL @ DEN", "JOKIC", "Nikola Jokic", "DEN", "LAL", "pra", "Pts+Reb+Ast", 52.5, "MORE", "STANDARD", "C", { offeredLower: true }),
  r("n8", "basketball", "NBA", "NBA_LAL_DEN", "LAL @ DEN", "DONCIC", "Luka Doncic", "LAL", "DEN", "pts", "Points", 31.5, "LESS", "STANDARD", "G", { offeredHigher: true }),
  r("w1", "basketball", "WNBA", "WNBA_NY_LV", "NY @ LV", "STEWART", "Breanna Stewart", "NY", "LV", "pts", "Points", 19.5, "MORE", "STANDARD", "F"),
  r("w2", "basketball", "WNBA", "WNBA_NY_LV", "NY @ LV", "WILSON", "A'ja Wilson", "LV", "NY", "reb", "Rebounds", 10.5, "MORE", "STANDARD", "C"),
  r("w3", "basketball", "WNBA", "WNBA_NY_LV", "NY @ LV", "IVES", "Sabrina Ionescu", "NY", "LV", "pra", "Pts+Reb+Ast", 24.5, "LESS", "STANDARD", "G", { offeredHigher: true }),
  r("f1", "gridiron", "NFL", "NFL_KC_BUF", "KC @ BUF", "MAHOMES", "Patrick Mahomes", "KC", "BUF", "pass_yds", "Passing Yards", 268.5, "LESS", "STANDARD", "QB", { offeredHigher: true }),
  r("f2", "gridiron", "NFL", "NFL_KC_BUF", "KC @ BUF", "MAHOMES", "Patrick Mahomes", "KC", "BUF", "pass_rush_yds", "Pass+Rush Yds", 289.5, "LESS", "STANDARD", "QB"),
  r("f3", "gridiron", "NFL", "NFL_KC_BUF", "KC @ BUF", "KELCE", "Travis Kelce", "KC", "BUF", "rec_yds", "Receiving Yards", 62.5, "MORE", "STANDARD", "TE"),
  r("f4", "gridiron", "NFL", "NFL_KC_BUF", "KC @ BUF", "COOK", "James Cook", "BUF", "KC", "rush_yds", "Rushing Yards", 71.5, "MORE", "STANDARD", "RB"),
  r("f5", "gridiron", "NFL", "NFL_KC_BUF", "KC @ BUF", "ALLEN", "Josh Allen", "BUF", "KC", "pass_yds", "Passing Yards", 249.5, "MORE", "DEMON", "QB"),
  r("f6", "gridiron", "NFL", "NFL_KC_BUF", "KC @ BUF", "KINC", "Harrison Butker", "KC", "BUF", "fg_made", "FG Made", 1.5, "MORE", "GOBLIN", "K"),
  r("f7", "gridiron", "NFL", "NFL_KC_BUF", "KC @ BUF", "HUNTER", "Taron Johnson", "BUF", "KC", "def_tackles", "Tackles", 5.5, "MORE", "STANDARD", "DEF"),
  r("c1", "gridiron", "CFB", "CFB_CFP_1", "CFP Semifinal", "SAYIN", "Julian Sayin", "OHIO", "MIAMI", "pass_yds", "Passing Yards", 241.5, "MORE", "STANDARD", "QB"),
  r("c2", "gridiron", "CFB", "CFB_CFP_1", "CFP Semifinal", "SMITH", "Jeremiah Smith", "OHIO", "MIAMI", "rec_yds", "Receiving Yards", 89.5, "MORE", "STANDARD", "WR"),
  r("c3", "gridiron", "CFB", "CFB_REG_1", "Regular season", "GENERIC_QB", "Unlisted CFB QB", "AAA", "BBB", "pass_yds", "Passing Yards", 220.5, "MORE", "STANDARD", "QB"),
  r("m1", "baseball", "MLB", "MLB_NYY_BOS", "NYY @ BOS", "JUDGE", "Aaron Judge", "NYY", "BOS", "h", "Hits", 1.5, "MORE", "STANDARD", "BAT"),
  r("m2", "baseball", "MLB", "MLB_NYY_BOS", "NYY @ BOS", "JUDGE", "Aaron Judge", "NYY", "BOS", "hits_runs_rbi", "Hits+Runs+RBIs", 0.5, "MORE", "GOBLIN", "BAT"),
  r("m3", "baseball", "MLB", "MLB_NYY_BOS", "NYY @ BOS", "SOTO", "Juan Soto", "NYY", "BOS", "hits_runs_rbi", "Hits+Runs+RBIs", 0.5, "MORE", "STANDARD", "BAT"),
  r("m4", "baseball", "MLB", "MLB_NYY_BOS", "NYY @ BOS", "COLE", "Gerrit Cole", "NYY", "BOS", "k", "Strikeouts", 6.5, "MORE", "STANDARD", "P"),
  r("m5", "baseball", "MLB", "MLB_NYY_BOS", "NYY @ BOS", "DEVERS", "Rafael Devers", "BOS", "NYY", "tb", "Total Bases", 2.5, "LESS", "STANDARD", "BAT", { offeredHigher: true }),
  r("u1", "combat", "UFC", "UFC_319", "UFC 319", "A", "Fighter A", "RED", "BLUE", "sig_strikes", "Sig. Strikes", 84.5, "MORE", "STANDARD", "MMA"),
  r("u2", "combat", "UFC", "UFC_319", "UFC 319", "B", "Fighter B", "BLUE", "RED", "sig_strikes", "Sig. Strikes", 72.5, "LESS", "STANDARD", "MMA"),
  r("s1", "soccer", "EPL", "EPL_1", "ARS v MCI", "SAKA", "Bukayo Saka", "ARS", "MCI", "shots", "Shots", 2.5, "MORE", "STANDARD", "W"),
  r("s2", "soccer", "EPL", "EPL_1", "ARS v MCI", "HAALAND", "Erling Haaland", "MCI", "ARS", "shots", "Shots", 3.5, "MORE", "STANDARD", "F"),
  r("l1", "gridiron", "CFL", "CFL_1", "WPG @ TOR", "FORD", "Tre Ford", "WPG", "TOR", "pass_yds", "Passing Yards", 278.5, "MORE", "STANDARD", "QB"),
  r("h1", "hockey", "NHL", "NHL_1", "COL @ DAL", "MACK", "Nathan MacKinnon", "COL", "DAL", "sog", "Shots on Goal", 3.5, "MORE", "STANDARD", "C"),
  r("t1", "racket", "ATP", "ATP_1", "Final", "SINNER", "Jannik Sinner", "ITA", "ESP", "aces", "Aces", 8.5, "MORE", "STANDARD", "S"),
];

export const DEMO_HAR = {
  log: {
    version: "1.2",
    creator: { name: "pillars-synthetic", version: "1" },
    entries: [
      {
        startedDateTime: "2026-08-27T16:00:00.000Z",
        request: { method: "GET", url: "https://api.prizepicks.com/projections" },
        response: {
          status: 200,
          content: {
            mimeType: "application/json",
            text: JSON.stringify({ data: DEMO_BOARD }),
          },
        },
      },
    ],
  },
  _pillars: { kind: "SYNTHETIC_HAR", note: "Not a live capture. Passing this does not prove historical HAR compatibility." },
};
