"""Integrity failure codes. These are states, not probability knobs."""

from enum import Enum


class FailureCode(str, Enum):
    EVENT_WORLD_INVALID = "EVENT_WORLD_INVALID"
    PRIMITIVE_CONSERVATION_FAILURE = "PRIMITIVE_CONSERVATION_FAILURE"
    DERIVED_IDENTITY_FAILURE = "DERIVED_IDENTITY_FAILURE"
    UNVERIFIED_MARKET_DEFINITION = "UNVERIFIED_MARKET_DEFINITION"
    QUARTER_PLUGIN_INCOMPLETE = "QUARTER_PLUGIN_INCOMPLETE"
    UNIT_MISMATCH = "UNIT_MISMATCH"
    UNKNOWN_PLATFORM_RULE = "UNKNOWN_PLATFORM_RULE"
    UNKNOWN_REBOOT_RULE = "UNKNOWN_REBOOT_RULE"
    UNKNOWN_PARTICIPATION_RULE = "UNKNOWN_PARTICIPATION_RULE"
    ENTRY_CONTRACT_INCOMPLETE = "ENTRY_CONTRACT_INCOMPLETE"
    PLATFORM_SETTLEMENT_UNRESOLVED = "PLATFORM_SETTLEMENT_UNRESOLVED"
    LEADERBOARD_EV_UNIDENTIFIED = "LEADERBOARD_EV_UNIDENTIFIED"
    SPORT_STAT_REVISION_AFTER_SETTLEMENT = "SPORT_STAT_REVISION_AFTER_SETTLEMENT"
    GOBLIN_SELECTION_FORBIDDEN = "GOBLIN_SELECTION_FORBIDDEN"
    OFFERED_SIDE_UNKNOWN = "OFFERED_SIDE_UNKNOWN"
    LINEAGE_STAGE_SKIPPED = "LINEAGE_STAGE_SKIPPED"
    LINEAGE_HASH_MUTATION = "LINEAGE_HASH_MUTATION"
    PRESEASON_RULE_UNVERIFIED = "PRESEASON_RULE_UNVERIFIED"
    CFB_PLAYER_NOT_IN_REBOOT_REGISTRY = "CFB_PLAYER_NOT_IN_REBOOT_REGISTRY"
    CFB_PHASE_NOT_PLAYOFF = "CFB_PHASE_NOT_PLAYOFF"
    PARTIAL_BOARD_NO_REBOOT = "PARTIAL_BOARD_NO_REBOOT"
    SCHEMA_HASH_MISMATCH = "SCHEMA_HASH_MISMATCH"
    BOARD_ACCOUNTING_MISMATCH = "BOARD_ACCOUNTING_MISMATCH"
