"""Permanent algorithm catalog. Source of truth for configs/algorithm_registry.json."""
from __future__ import annotations

from typing import Any

CONSTITUTION_VERSION = "DCM-ALGORITHM-CONSTITUTION-v1.0.0-20260903"
SCHEMA = "pillars_dcm.algorithm_registry.v1"


def _a(
    algorithm_id: str,
    canonical_name: str,
    algorithm_family: str,
    lifecycle: str,
    *,
    implementation_module: str,
    implementation_symbol: str,
    runtime_producer: str,
    runtime_consumer: str,
    applicability_contract: str,
    input_contract: str,
    output_contract: str,
    semantic_scope: str,
    fallback_algorithm_id: str | None = None,
    portability_class: str = "STDLIB",
    determinism_class: str = "DETERMINISTIC",
    time_complexity_expectation: str = "O(n)",
    memory_complexity_expectation: str = "O(n)",
    token_cost_expectation: str = "NONE",
    storage_cost_expectation: str = "LOW",
    test_ids: tuple[str, ...] = ("test_algorithm_constitution",),
    benchmark_ids: tuple[str, ...] = ("benchmarks/algorithm_frontier/core_smoke.py",),
    requirement_trace_ids: tuple[str, ...] = ("REQ-ALG-CONST-R0",),
    dependency_requirements: tuple[str, ...] = (),
) -> dict[str, Any]:
    tests = list(test_ids)
    if lifecycle in {"REQUIRED_CORE", "REQUIRED_CONDITIONAL"} and "test_algorithm_core" not in tests:
        tests.append("test_algorithm_core")
    if fallback_algorithm_id and "test_algorithm_fallbacks" not in tests:
        tests.append("test_algorithm_fallbacks")
    return {
        "algorithm_id": algorithm_id,
        "canonical_name": canonical_name,
        "algorithm_family": algorithm_family,
        "lifecycle": lifecycle,
        "applicability_contract": applicability_contract,
        "input_contract": input_contract,
        "output_contract": output_contract,
        "semantic_scope": semantic_scope,
        "implementation_module": implementation_module,
        "implementation_symbol": implementation_symbol,
        "runtime_producer": runtime_producer,
        "runtime_consumer": runtime_consumer,
        "fallback_algorithm_id": fallback_algorithm_id,
        "dependency_requirements": list(dependency_requirements),
        "determinism_class": determinism_class,
        "time_complexity_expectation": time_complexity_expectation,
        "memory_complexity_expectation": memory_complexity_expectation,
        "token_cost_expectation": token_cost_expectation,
        "storage_cost_expectation": storage_cost_expectation,
        "portability_class": portability_class,
        "benchmark_ids": list(benchmark_ids),
        "test_ids": tests,
        "audit_event_types": ["ALGORITHM_SELECTED"],
        "requirement_trace_ids": list(requirement_trace_ids),
        "introduced_version": CONSTITUTION_VERSION,
        "superseding_adr": None,
        "retired_version": None,
    }


ALGORITHM_RECORDS: tuple[dict[str, Any], ...] = (
    # --- SEARCH ---
    _a("ALG-SEARCH-001", "Exact hash lookup", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="exact_hash_lookup",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="canonical identity/hash key exists",
       input_contract="hash table + exact key", output_contract="value or KeyError",
       semantic_scope="IDs, hashes, players, teams, events, props, claims",
       time_complexity_expectation="O(1) expected"),
    _a("ALG-SEARCH-002", "Composite-key lookup", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="composite_key",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.ingest.board",
       applicability_contract="structured (sport,event,subject,market,cutoff) retrieval",
       input_contract="ordered key parts", output_contract="tuple key",
       semantic_scope="HAR/board composite identity"),
    _a("ALG-SEARCH-003", "Binary search / bisect", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="binary_search",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="ordered immutable arrays/ranges",
       input_contract="sorted sequence + value", output_contract="index or -1",
       semantic_scope="ordered cutoffs, lines, times",
       time_complexity_expectation="O(log n)"),
    _a("ALG-SEARCH-004", "Inverted Index", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="InvertedIndex",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="tokenized research/log/source text",
       input_contract="doc_id + terms", output_contract="postings lists",
       semantic_scope="research, logs, source text"),
    _a("ALG-SEARCH-005", "BM25", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="bm25",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="lexical ranking of research documents",
       input_contract="query terms + documents", output_contract="per-document scores",
       semantic_scope="lexical research ranking"),
    _a("ALG-SEARCH-006", "BM25F", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="bm25f",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="multi-field lexical ranking",
       input_contract="query + field documents + weights", output_contract="scores",
       semantic_scope="title/body/alias fields"),
    _a("ALG-SEARCH-007", "Boolean postings intersection", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="InvertedIndex.boolean_and",
       runtime_producer="InvertedIndex", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="structured multi-condition retrieval",
       input_contract="term list", output_contract="sorted doc ids",
       semantic_scope="AND retrieval over postings"),
    _a("ALG-SEARCH-008", "Aho-Corasick", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="AhoCorasick",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="many aliases in one document pass",
       input_contract="patterns + text", output_contract="(index, pattern) hits",
       semantic_scope="player/team alias scan"),
    _a("ALG-SEARCH-009", "Trie / Radix Trie", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="Trie",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="name/alias/prefix resolution",
       input_contract="word + optional value", output_contract="prefix completions",
       semantic_scope="canonical alias prefixes"),
    _a("ALG-SEARCH-010", "Fuzzy edit-distance retrieval", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="fuzzy_retrieve",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="exact/alias lookup already failed",
       input_contract="query + candidates + max_distance", output_contract="(candidate, distance)",
       semantic_scope="misspellings/variant identities",
       fallback_algorithm_id="ALG-SEARCH-001"),
    _a("ALG-SEARCH-011", "MinHash", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="minhash_signature",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.research.claims",
       applicability_contract="near-duplicate research detection",
       input_contract="token iterable", output_contract="signature tuple",
       semantic_scope="research lineage"),
    _a("ALG-SEARCH-012", "SimHash", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="simhash",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.research.claims",
       applicability_contract="fast textual duplication detection",
       input_contract="tokens", output_contract="64-bit digest",
       semantic_scope="syndicated copies"),
    _a("ALG-SEARCH-013", "LSH", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="LSHIndex",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="candidate duplicate/similarity retrieval",
       input_contract="banded MinHash signatures", output_contract="candidate keys",
       semantic_scope="near-duplicate candidates"),
    _a("ALG-SEARCH-014", "Reciprocal Rank Fusion", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="reciprocal_rank_fusion",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="hybrid lexical+semantic result merge",
       input_contract="ranked lists", output_contract="fused ranking",
       semantic_scope="hybrid retrieval"),
    _a("ALG-SEARCH-015", "Maximal Marginal Relevance", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="maximal_marginal_relevance",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.research.batch",
       applicability_contract="prevent redundant research/source results",
       input_contract="candidates + relevance + similarity", output_contract="diverse subset",
       semantic_scope="source result diversification"),
    _a("ALG-SEARCH-016", "Graph BFS", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="bfs",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.research.dependency_graph",
       applicability_contract="evidence/dependency traversal",
       input_contract="adjacency + start", output_contract="visit order",
       semantic_scope="EvidenceGraph/dependency graph"),
    _a("ALG-SEARCH-017", "Graph DFS", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="dfs",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.research.dependency_graph",
       applicability_contract="depth-first provenance walk",
       input_contract="adjacency + start", output_contract="visit order",
       semantic_scope="provenance"),
    _a("ALG-SEARCH-018", "Cost-based query planning", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.selection", implementation_symbol="AlgorithmSelectionEngine.select",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="every DCM lookup",
       input_contract="problem class + runtime context", output_contract="ALGORITHM_SELECTED",
       semantic_scope="cheapest exact index before expensive search"),
    _a("ALG-SEARCH-019", "Weighted Set Cover search", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="weighted_set_cover",
       runtime_producer="dcm.algorithms.scheduling", runtime_consumer="dcm.research.batch",
       applicability_contract="shared evidence can cover many board requirements",
       input_contract="universe + weighted sets", output_contract="chosen set ids + uncovered",
       semantic_scope="research bundles",
       requirement_trace_ids=("REQ-ALG-CONST-R0", "REQ-ALG-SETCOVER")),
    _a("ALG-SEARCH-020", "Submodular maximization", "SEARCH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="submodular_lazy_greedy",
       runtime_producer="dcm.algorithms.scheduling", runtime_consumer="dcm.research.batch",
       applicability_contract="marginal information after collected evidence",
       input_contract="items + gain/cost callables", output_contract="selected items",
       semantic_scope="Research OS scheduling",
       requirement_trace_ids=("REQ-ALG-CONST-R0", "REQ-ALG-SUBMODULAR")),
    _a("ALG-SEARCH-021", "Block-Max WAND / WAND", "SEARCH", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.searching", implementation_symbol="wand_topk",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="large posting indexes needing Top-K",
       input_contract="query + documents + k", output_contract="top-k (doc, score)",
       semantic_scope="fast Top-K lexical retrieval",
       fallback_algorithm_id="ALG-SEARCH-005",
       time_complexity_expectation="O(n log k) portable"),
    _a("ALG-SEARCH-022", "Bidirectional graph search", "SEARCH", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.searching", implementation_symbol="bidirectional_search",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.algorithms.graph",
       applicability_contract="deep provenance/dependency paths",
       input_contract="adj + start + goal", output_contract="path or None",
       semantic_scope="provenance paths",
       fallback_algorithm_id="ALG-SEARCH-016"),
    _a("ALG-SEARCH-023", "HNSW", "SEARCH", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.searching", implementation_symbol="brute_force_cosine",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="semantic ANN when portable index installed; else brute cosine after structured filter",
       input_contract="query vector + corpus", output_contract="top-k cosine",
       semantic_scope="semantic research retrieval",
       fallback_algorithm_id="ALG-SEARCH-005",
       portability_class="OPTIONAL_PACKAGE"),
    _a("ALG-SEARCH-024", "DiskANN", "SEARCH", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="very large disk-resident semantic corpus",
       input_contract="SSD-backed vectors", output_contract="ANN hits",
       semantic_scope="Drive-scale semantic archives",
       fallback_algorithm_id="ALG-SEARCH-023", portability_class="NOT_PORTABLE_CHALLENGER"),
    _a("ALG-SEARCH-025", "IVF-PQ", "SEARCH", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="compressed massive vector retrieval",
       input_contract="quantized vectors", output_contract="ANN hits",
       semantic_scope="large vector stores",
       fallback_algorithm_id="ALG-SEARCH-023", portability_class="NOT_PORTABLE_CHALLENGER"),
    _a("ALG-SEARCH-026", "Product Quantization", "SEARCH", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="vector-memory reduction",
       input_contract="high-dim vectors", output_contract="codes",
       semantic_scope="vector compression",
       fallback_algorithm_id="ALG-SEARCH-023", portability_class="NOT_PORTABLE_CHALLENGER"),
    # --- INDEX ---
    _a("ALG-INDEX-001", "Python hash tables", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="hash_table",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="L0 hot runtime index",
       applicability_contract="in-memory exact identity",
       input_contract="key/value pairs", output_contract="dict",
       semantic_scope="L0 hot runtime index"),
    _a("ALG-INDEX-002", "SQLite B/B+ tree indexes", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="open_memory_index",
       runtime_producer="dcm.runtime.store.IndexedStore", runtime_consumer="dcm.research.statepack",
       applicability_contract="structured persistent index",
       input_contract="SQL table", output_contract="B-tree index",
       semantic_scope="L1 structured persistent index", portability_class="SQLITE"),
    _a("ALG-INDEX-003", "Composite B-tree indexes", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="sqlite_composite_index",
       runtime_producer="dcm.runtime.store.IndexedStore", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="sport/event/player/market/time",
       input_contract="table + columns", output_contract="named index",
       semantic_scope="composite retrieval", portability_class="SQLITE"),
    _a("ALG-INDEX-004", "Covering indexes", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="sqlite_composite_index",
       runtime_producer="dcm.runtime.store.IndexedStore", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="avoid unnecessary record loads",
       input_contract="covering column set", output_contract="index",
       semantic_scope="L1 covering lookup", portability_class="SQLITE",
       fallback_algorithm_id="ALG-INDEX-003"),
    _a("ALG-INDEX-005", "Partial indexes", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="sqlite_composite_index",
       runtime_producer="dcm.runtime.store.IndexedStore", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="current/fresh/active subsets",
       input_contract="filtered rows", output_contract="partial index",
       semantic_scope="active subsets", portability_class="SQLITE",
       fallback_algorithm_id="ALG-INDEX-003"),
    _a("ALG-INDEX-006", "Radix/Patricia Trie", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="Trie",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="entity aliases",
       input_contract="strings", output_contract="prefix index",
       semantic_scope="alias index"),
    _a("ALG-INDEX-007", "Inverted index structure", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="InvertedIndex",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="full-text",
       input_contract="documents", output_contract="postings",
       semantic_scope="full-text index"),
    _a("ALG-INDEX-008", "Bitmap indexes / Python bitsets", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="Bitset",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="large categorical intersections",
       input_contract="integer ids", output_contract="bitset + intersection",
       semantic_scope="categorical filters"),
    _a("ALG-INDEX-009", "Bloom Filter", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="BloomFilter",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="avoid unnecessary Drive/shard reads",
       input_contract="keys", output_contract="membership maybe",
       semantic_scope="shard rejection"),
    _a("ALG-INDEX-010", "MinHash/LSH index", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="MinHashLSHIndex",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="research lineage similarity",
       input_contract="signatures", output_contract="candidate keys",
       semantic_scope="research lineage"),
    _a("ALG-INDEX-011", "SimHash index", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="SimHashIndex",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="fast duplicate lookup",
       input_contract="simhash digests", output_contract="nearest keys",
       semantic_scope="duplicate lookup"),
    _a("ALG-INDEX-012", "CSR adjacency index", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="CSRGraph",
       runtime_producer="dcm.algorithms.graph", runtime_consumer="dcm.research.dependency_graph",
       applicability_contract="EvidenceGraph/dependency graph",
       input_contract="edge list", output_contract="CSR adjacency",
       semantic_scope="forward neighbors"),
    _a("ALG-INDEX-013", "CSC reverse adjacency", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="CSRGraph.predecessors",
       runtime_producer="dcm.algorithms.graph", runtime_consumer="dcm.research.dependency_graph",
       applicability_contract="reverse dependency lookup",
       input_contract="CSR graph + node", output_contract="predecessors",
       semantic_scope="reverse edges"),
    _a("ALG-INDEX-014", "Hypergraph incidence index", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="HypergraphIncidence",
       runtime_producer="dcm.algorithms.graph", runtime_consumer="dcm.research.batch",
       applicability_contract="one evidence item → many props",
       input_contract="edge id + members", output_contract="incidence maps",
       semantic_scope="shared research fanout"),
    _a("ALG-INDEX-015", "Bitemporal compound index", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="bitemporal_key",
       runtime_producer="dcm.research.statepack", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="valid-time + observed-time",
       input_contract="entity, claim, valid, observed, cutoff", output_contract="compound key",
       semantic_scope="as-of evidence"),
    _a("ALG-INDEX-016", "SHA-256 content-address index", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="content_address",
       runtime_producer="dcm.contracts.hashes", runtime_consumer="dcm.research.research_store",
       applicability_contract="research and artifact deduplication",
       input_contract="canonical object/bytes", output_contract="sha256",
       semantic_scope="content identity"),
    _a("ALG-INDEX-017", "Merkle Tree / Merkle DAG", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="merkle_root",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="run manifest",
       applicability_contract="immutable run verification",
       input_contract="leaf hashes/values", output_contract="root hash",
       semantic_scope="run integrity"),
    _a("ALG-INDEX-018", "Git object/commit identity", "INDEX", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="git_blob_identity",
       runtime_producer="dcm.release", runtime_consumer="release manifest",
       applicability_contract="code/version provenance",
       input_contract="blob bytes", output_contract="content hash",
       semantic_scope="git provenance"),
    _a("ALG-INDEX-019", "Roaring Bitmap", "INDEX", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="Bitset",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="high-cardinality compressed categorical index when package available",
       input_contract="integer ids", output_contract="compressed bitset",
       semantic_scope="categorical intersection",
       fallback_algorithm_id="ALG-INDEX-008", portability_class="OPTIONAL_PACKAGE"),
    _a("ALG-INDEX-020", "XOR Filter", "INDEX", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="XorFilterFallback",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="static immutable shards",
       input_contract="static key set", output_contract="membership filter",
       semantic_scope="immutable shard membership",
       fallback_algorithm_id="ALG-INDEX-009"),
    _a("ALG-INDEX-021", "Cuckoo Filter", "INDEX", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="CuckooFilter",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="mutable membership indexes",
       input_contract="keys", output_contract="membership",
       semantic_scope="mutable filters",
       fallback_algorithm_id="ALG-INDEX-009"),
    _a("ALG-INDEX-022", "Reachability index", "INDEX", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.searching", implementation_symbol="bfs",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.research.evidence_graph",
       applicability_contract="large provenance DAGs",
       input_contract="graph + source", output_contract="reachable set",
       semantic_scope="provenance blast-radius",
       fallback_algorithm_id="ALG-SEARCH-016"),
    _a("ALG-INDEX-023", "HNSW index", "INDEX", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.searching", implementation_symbol="brute_force_cosine",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="semantic retrieval when installed",
       input_contract="vectors", output_contract="ANN index",
       semantic_scope="semantic index",
       fallback_algorithm_id="ALG-SEARCH-023", portability_class="OPTIONAL_PACKAGE"),
    _a("ALG-INDEX-024", "DiskANN index", "INDEX", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="Drive-scale semantic archives",
       input_contract="SSD vectors", output_contract="disk ANN",
       semantic_scope="scale-up semantic",
       fallback_algorithm_id="ALG-INDEX-023", portability_class="NOT_PORTABLE_CHALLENGER"),
    _a("ALG-INDEX-025", "PGM-index", "INDEX", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="massive ordered immutable datasets",
       input_contract="sorted keys", output_contract="learned index",
       semantic_scope="learned indexes",
       fallback_algorithm_id="ALG-INDEX-002", portability_class="NOT_PORTABLE_CHALLENGER"),
    _a("ALG-INDEX-026", "ALEX/RMI learned indexes", "INDEX", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="benchmark against conventional indexes only",
       input_contract="key distribution", output_contract="learned index",
       semantic_scope="learned indexes",
       fallback_algorithm_id="ALG-INDEX-002", portability_class="NOT_PORTABLE_CHALLENGER"),
    # --- SORT ---
    _a("ALG-SORT-001", "Timsort", "SORT", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="timsort",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.model.ranking.rank_candidates",
       applicability_contract="final ordered outputs and partially ordered real-world data",
       input_contract="iterable + key", output_contract="stable sorted list",
       semantic_scope="deterministic final ranking"),
    _a("ALG-SORT-002", "Heap / priority heaps", "SORT", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="heap_topk",
       runtime_producer="dcm.algorithms.scheduling.LazyGreedyScheduler", runtime_consumer="dcm.research.batch",
       applicability_contract="research scheduler live queue",
       input_contract="items + k", output_contract="priority subset",
       semantic_scope="research scheduler"),
    _a("ALG-SORT-003", "heapq.nlargest/nsmallest", "SORT", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="heap_topk",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="Top-K candidate extraction when k << n",
       input_contract="sequence + k", output_contract="top-k list",
       semantic_scope="Top-100/25/frontier"),
    _a("ALG-SORT-004", "Quickselect", "SORT", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="quickselect",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="large partial-selection workloads",
       input_contract="sequence + k", output_contract="kth item",
       semantic_scope="Top-N isolation",
       fallback_algorithm_id="ALG-SORT-003"),
    _a("ALG-SORT-005", "External Merge Sort", "SORT", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="external_merge_sort",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="data larger than available memory",
       input_contract="sorted chunks", output_contract="merged sequence",
       semantic_scope="research/log shards"),
    _a("ALG-SORT-006", "K-way merge / loser tree", "SORT", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="k_way_merge",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="merge research/log shards",
       input_contract="sorted streams", output_contract="merged list",
       semantic_scope="shard merge"),
    _a("ALG-SORT-007", "Lexicographic stable multi-key sorting", "SORT", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="multi_key_sort",
       runtime_producer="dcm.model.ranking", runtime_consumer="frozen forecast ranking",
       applicability_contract="final tie-breaking",
       input_contract="items + key functions", output_contract="stable multi-key order",
       semantic_scope="deterministic board/results"),
    _a("ALG-SORT-008", "Topological Sort / Kahn", "SORT", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="topological_kahn",
       runtime_producer="dcm.signals.compiler", runtime_consumer="dcm.runtime.dag",
       applicability_contract="dependency execution order",
       input_contract="nodes + edges", output_contract="topo order or TOPO_CYCLE",
       semantic_scope="research/operator dependencies"),
    _a("ALG-SORT-009", "Introselect", "SORT", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="introselect",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="robust selection when quickselect degrades",
       input_contract="sequence + k", output_contract="kth item",
       semantic_scope="robust partial select",
       fallback_algorithm_id="ALG-SORT-004"),
    _a("ALG-SORT-010", "Radix Sort", "SORT", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="radix_sort",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="large integer IDs where profiling proves a win",
       input_contract="integers", output_contract="sorted integers",
       semantic_scope="integer keys",
       fallback_algorithm_id="ALG-SORT-001"),
    _a("ALG-SORT-011", "Counting Sort", "SORT", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="counting_sort",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="small dense integer ranges",
       input_contract="integers", output_contract="sorted integers",
       semantic_scope="dense integer keys",
       fallback_algorithm_id="ALG-SORT-001"),
    _a("ALG-SORT-012", "Bucket Sort", "SORT", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.sorting", implementation_symbol="bucket_sort",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="defined line/time bands",
       input_contract="floats + bucket count", output_contract="sorted floats",
       semantic_scope="line/time bands",
       fallback_algorithm_id="ALG-SORT-001"),
    # --- GROUP ---
    _a("ALG-GROUP-001", "Composite-key hash grouping", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="composite_group",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.ingest.board",
       applicability_contract="HAR exact grouping; no ML replacement of known relationships",
       input_contract="rows + key fields", output_contract="hash groups",
       semantic_scope="HAR decomposition"),
    _a("ALG-GROUP-002", "Union-Find / DSU", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="UnionFind",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.identity.resolve",
       applicability_contract="confirmed alias/entity merges",
       input_contract="union operations", output_contract="components",
       semantic_scope="entity/lineage merges"),
    _a("ALG-GROUP-003", "Connected Components", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="connected_components",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.dependency_graph",
       applicability_contract="independent event/research groups",
       input_contract="undirected edges", output_contract="component lists",
       semantic_scope="research communities"),
    _a("ALG-GROUP-004", "Tarjan SCC", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="tarjan_scc",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.signals.compiler",
       applicability_contract="dependency-cycle detection",
       input_contract="directed adj", output_contract="strongly connected components",
       semantic_scope="cycle safety"),
    _a("ALG-GROUP-005", "Kahn DAG layering", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="kahn_layers",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.batch",
       applicability_contract="stage/group execution",
       input_contract="nodes + edges", output_contract="layers",
       semantic_scope="research stages"),
    _a("ALG-GROUP-006", "Hypergraph incidence grouping", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="hypergraph_group",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.batch",
       applicability_contract="shared research fanout",
       input_contract="edge membership", output_contract="grouped members",
       semantic_scope="one evidence → many props"),
    _a("ALG-GROUP-007", "Weighted Set Cover", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="set_cover_groups",
       runtime_producer="dcm.algorithms.scheduling", runtime_consumer="dcm.research.batch",
       applicability_contract="research bundles covering maximum board",
       input_contract="universe + bundles + weights", output_contract="chosen bundles",
       semantic_scope="research bundles",
       requirement_trace_ids=("REQ-ALG-CONST-R0", "REQ-ALG-SETCOVER")),
    _a("ALG-GROUP-008", "Submodular grouping", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.searching", implementation_symbol="submodular_lazy_greedy",
       runtime_producer="dcm.algorithms.scheduling", runtime_consumer="dcm.research.batch",
       applicability_contract="maximum marginal coverage",
       input_contract="items + gain", output_contract="selected groups",
       semantic_scope="marginal coverage",
       requirement_trace_ids=("REQ-ALG-CONST-R0", "REQ-ALG-SUBMODULAR")),
    _a("ALG-GROUP-009", "Constraint-aware grouping", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="constraint_group",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.sports.common.plugin",
       applicability_contract="must-link/cannot-link sports semantics",
       input_contract="items + constraints", output_contract="legal groups",
       semantic_scope="sport semantics"),
    _a("ALG-GROUP-010", "Hierarchical Agglomerative", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="hierarchical_agglomerative",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="nested comparable classes; never override HAR identifiers",
       input_contract="labels + distance + threshold", output_contract="clusters",
       semantic_scope="nested comparable classes"),
    _a("ALG-GROUP-011", "Leiden community detection", "GROUP", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="louvain_fallback",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="large dependency graphs when package installed",
       input_contract="edges", output_contract="communities",
       semantic_scope="dependency communities",
       fallback_algorithm_id="ALG-GROUP-003", portability_class="OPTIONAL_PACKAGE"),
    _a("ALG-GROUP-012", "Louvain", "GROUP", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="louvain_fallback",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="graph community fallback when Leiden unavailable",
       input_contract="edges", output_contract="communities",
       semantic_scope="graph community fallback",
       fallback_algorithm_id="ALG-GROUP-003"),
    _a("ALG-GROUP-013", "HDBSCAN", "GROUP", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="dbscan_fallback",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="player/role/context archetypes; never replace HAR relationships",
       input_contract="labels + distance", output_contract="density clusters",
       semantic_scope="latent archetypes",
       fallback_algorithm_id="ALG-GROUP-010", portability_class="OPTIONAL_PACKAGE"),
    _a("ALG-GROUP-014", "DBSCAN", "GROUP", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="dbscan_fallback",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="density clusters fallback",
       input_contract="labels + distance + eps", output_contract="clusters",
       semantic_scope="density clusters",
       fallback_algorithm_id="ALG-GROUP-010"),
    _a("ALG-GROUP-015", "OPTICS", "GROUP", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="variable density clustering",
       input_contract="points", output_contract="reachability",
       semantic_scope="variable density",
       fallback_algorithm_id="ALG-GROUP-014", portability_class="NOT_PORTABLE_CHALLENGER"),
    _a("ALG-GROUP-016", "Spectral Clustering", "GROUP", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="non-convex relationship groups",
       input_contract="affinity", output_contract="clusters",
       semantic_scope="non-convex groups",
       fallback_algorithm_id="ALG-GROUP-003", portability_class="NOT_PORTABLE_CHALLENGER"),
    _a("ALG-GROUP-017", "Biclustering / Co-clustering", "GROUP", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="composite_group",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="player × context/stat groups when useful to comparables",
       input_contract="matrix-like rows", output_contract="co-clusters",
       semantic_scope="player x context",
       fallback_algorithm_id="ALG-GROUP-001"),
    _a("ALG-GROUP-018", "Gaussian Mixture Models", "GROUP", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="gaussian_mixture_1d",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="soft archetype membership; never override HAR truth",
       input_contract="1-D values + k", output_contract="component mean/weight/variance",
       semantic_scope="soft archetypes"),
    _a("ALG-GROUP-019", "Affinity Propagation", "GROUP", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="exemplar discovery",
       input_contract="similarity", output_contract="exemplars",
       semantic_scope="exemplars",
       fallback_algorithm_id="ALG-GROUP-010", portability_class="NOT_PORTABLE_CHALLENGER"),
    _a("ALG-GROUP-020", "BIRCH", "GROUP", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.grouping", implementation_symbol="hierarchical_agglomerative",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="HarAlgorithmExecutionPlan",
       applicability_contract="huge feature populations",
       input_contract="labels + distance", output_contract="clusters",
       semantic_scope="large populations",
       fallback_algorithm_id="ALG-GROUP-010"),
    _a("ALG-GROUP-021", "Graph embeddings + clustering", "GROUP", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
       applicability_contract="latent dependency grouping",
       input_contract="graph", output_contract="embedding clusters",
       semantic_scope="latent dependency",
       fallback_algorithm_id="ALG-GROUP-003", portability_class="NOT_PORTABLE_CHALLENGER"),
    # --- GRAPH / SCHED / CACHE ---
    _a("ALG-GRAPH-001", "CSR/CSC graph builder", "GRAPH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.graph", implementation_symbol="build_csr",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.dependency_graph",
       applicability_contract="typed evidence/dependency graphs",
       input_contract="edge list", output_contract="CSRGraph",
       semantic_scope="graph construction"),
    _a("ALG-GRAPH-002", "Cycle validation", "GRAPH", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.graph", implementation_symbol="cycles",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.signals.compiler",
       applicability_contract="reject invalid dependency cycles",
       input_contract="directed adj", output_contract="non-trivial SCCs",
       semantic_scope="cycle safety"),
    _a("ALG-SCHED-001", "Lazy-greedy CELF scheduler", "SCHED", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.scheduling", implementation_symbol="LazyGreedyScheduler",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.batch",
       applicability_contract="adaptive submodular weighted coverage",
       input_contract="action ids + gain/cost", output_contract="selected actions",
       semantic_scope="Research OS scheduler",
       requirement_trace_ids=("REQ-ALG-CONST-R0", "REQ-ALG-SUBMODULAR")),
    _a("ALG-SCHED-002", "Weighted set-cover scheduler", "SCHED", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.scheduling", implementation_symbol="cover_actions",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.batch",
       applicability_contract="shared acquisition covering many requirements",
       input_contract="universe + actions", output_contract="chosen actions",
       semantic_scope="AcquisitionAction packing",
       requirement_trace_ids=("REQ-ALG-CONST-R0", "REQ-ALG-SETCOVER")),
    _a("ALG-SCHED-003", "Deterministic value-density packing", "SCHED", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.scheduling", implementation_symbol="greedy_value_density_pack",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.batch",
       applicability_contract="budget-constrained batch packing fallback",
       input_contract="items + value/weight + capacity", output_contract="packed ids",
       semantic_scope="batch packing"),
    _a("ALG-SCHED-004", "First-fit decreasing packer", "SCHED", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.scheduling", implementation_symbol="first_fit_decreasing",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.batch",
       applicability_contract="constrained greedy first-fit/decreasing",
       input_contract="items + sizes + bin capacity", output_contract="bins",
       semantic_scope="host batch bins"),
    _a("ALG-SCHED-005", "CP-SAT batch packer", "SCHED", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.scheduling", implementation_symbol="greedy_value_density_pack",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.research.batch",
       applicability_contract="resource/dependency packing when solver available",
       input_contract="items + constraints", output_contract="packed batch",
       semantic_scope="resource packing",
       fallback_algorithm_id="ALG-SCHED-003", portability_class="OPTIONAL_PACKAGE"),
    _a("ALG-SCHED-006", "Contextual Thompson Sampling", "SCHED", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.ml_families", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="source routing",
       applicability_contract="source/query selection under authority constraints after sufficient history; SHADOW until promoted",
       input_contract="context + rewards", output_contract="source choice",
       semantic_scope="research source routing",
       fallback_algorithm_id="ALG-SEARCH-018", portability_class="STDLIB",
       determinism_class="STOCHASTIC_SHADOW"),
    _a("ALG-SCHED-007", "UCB / contextual UCB", "SCHED", "REQUIRED_CONDITIONAL",
       implementation_module="dcm.algorithms.ml_families", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmSelectionEngine", runtime_consumer="source routing",
       applicability_contract="research acquisition after history; SHADOW",
       input_contract="context + counts", output_contract="arm choice",
       semantic_scope="acquisition",
       fallback_algorithm_id="ALG-SEARCH-018", determinism_class="STOCHASTIC_SHADOW"),
    _a("ALG-SCHED-008", "EVSI / knowledge-gradient", "SCHED", "PERMANENT_CHALLENGER",
       implementation_module="dcm.algorithms.searching", implementation_symbol="not_active_challenger",
       runtime_producer="AlgorithmFrontierReview", runtime_consumer="frontier research tranche",
       applicability_contract="after baseline modeling, prioritize research changing Top-100/25/6",
       input_contract="unresolved facts + utility", output_contract="EVSI scores",
       semantic_scope="frontier VOI",
       fallback_algorithm_id="ALG-SCHED-001"),
    _a("ALG-CACHE-001", "LRU hot cache", "CACHE", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.cache", implementation_symbol="LRUCache",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.cache",
       applicability_contract="L0 current-run reuse",
       input_contract="key/value + capacity", output_contract="cached value",
       semantic_scope="hot runtime cache"),
    _a("ALG-CACHE-002", "LFU / adaptive hot cache", "CACHE", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.cache", implementation_symbol="LFUCache",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="dcm.research.cache",
       applicability_contract="frequency-biased hot objects",
       input_contract="key/value + capacity", output_contract="cached value",
       semantic_scope="adaptive cache",
       fallback_algorithm_id="ALG-CACHE-001"),
    _a("ALG-CACHE-003", "Bloom shard rejection cache", "CACHE", "REQUIRED_CORE",
       implementation_module="dcm.algorithms.indexing", implementation_symbol="BloomFilter",
       runtime_producer="HarAlgorithmExecutionPlan", runtime_consumer="Drive catalog",
       applicability_contract="negative membership before Drive reads",
       input_contract="keys", output_contract="maybe-contains",
       semantic_scope="Drive read avoidance"),
)

# ML / calibration / uncertainty / foundation-model families appended below via helper lists.


def _ml() -> tuple[dict[str, Any], ...]:
    rows: list[dict[str, Any]] = []
    core = [
        ("ALG-ML-TABULAR-001", "Elastic Net / ridge", "ML_TABULAR", "ridge_closed_form",
         "small structured linear baseline", "xs, ys, l2", "weights", "tabular baseline"),
        ("ALG-ML-TABULAR-010", "Quantile Regression", "ML_TABULAR", "empirical_quantile",
         "distribution/tails without mean-only collapse", "values + q", "quantile", "outcome tails"),
        ("ALG-ML-TIME-001", "EWMA", "ML_TIME", "ewma",
         "gradual drift", "value series", "smoothed series", "form/drift"),
        ("ALG-ML-TIME-002", "CUSUM", "ML_TIME", "cusum",
         "structural mean-shift detection", "value series", "change indexes", "role/scheme change"),
        ("ALG-ML-TIME-003", "Page-Hinkley", "ML_TIME", "page_hinkley",
         "drift/change detection", "value series", "change indexes", "source/parser drift"),
        ("ALG-ML-PROB-001", "Empirical Bayes shrinkage", "ML_PROB", "empirical_bayes_shrink",
         "sparse samples; hierarchical partial pooling portable form", "x,n,prior", "shrunk estimate", "sparse players"),
        ("ALG-CAL-001", "Isotonic Calibration", "CAL", "isotonic_regression",
         "probability calibration with monotone mapping", "scores + labels as xs/ys", "calibrated values", "calibration"),
        ("ALG-CAL-002", "Platt scaling", "CAL", "platt_scale",
         "probability calibration", "scores + labels", "a,b parameters", "calibration"),
        ("ALG-UNCERTAINTY-001", "Conformal Prediction (split)", "UNCERTAINTY", "split_conformal",
         "coverage-aware intervals; never convert width into probability", "residuals + alpha", "quantile width", "uncertainty"),
        ("ALG-UNCERTAINTY-004", "Isolation / z-score OOD", "UNCERTAINTY", "zscore_ood",
         "OOD/anomalies; widen epistemic uncertainty rather than false precision", "value + population", "score", "OOD"),
    ]
    for aid, name, fam, sym, appl, inp, out, scope in core:
        rows.append(_a(
            aid, name, fam, "REQUIRED_CORE",
            implementation_module="dcm.algorithms.ml_families", implementation_symbol=sym,
            runtime_producer="AlgorithmSelectionEngine",
            runtime_consumer="dcm.model.uncertainty" if fam in {"CAL", "UNCERTAINTY"} else "dcm.learning.registry",
            applicability_contract=appl, input_contract=inp, output_contract=out, semantic_scope=scope,
            test_ids=("test_algorithm_constitution", "test_algorithm_core", "test_algorithm_ml_stdlib"),
        ))
    conditional = [
        ("ALG-ML-TABULAR-002", "Generalized Linear Models", "ML_TABULAR", "ridge_closed_form", "ALG-ML-TABULAR-001",
         "market-specific distributions with portable linear fallback"),
        ("ALG-ML-PROB-003", "Mixture Models", "ML_PROB", "not_active_challenger", "ALG-GROUP-018",
         "multi-regime outcomes when identification holds"),
        ("ALG-UNCERTAINTY-002", "Mondrian Conformal", "UNCERTAINTY", "split_conformal", "ALG-UNCERTAINTY-001",
         "sport/market-conditioned coverage"),
        ("ALG-UNCERTAINTY-003", "Adaptive Conformal", "UNCERTAINTY", "split_conformal", "ALG-UNCERTAINTY-001",
         "drift-aware coverage"),
        ("ALG-UNCERTAINTY-005", "Mahalanobis OOD detection", "UNCERTAINTY", "zscore_ood", "ALG-UNCERTAINTY-004",
         "distribution distance when covariance is well-conditioned"),
    ]
    for aid, name, fam, sym, fb, appl in conditional:
        rows.append(_a(
            aid, name, fam, "REQUIRED_CONDITIONAL",
            implementation_module="dcm.algorithms.ml_families", implementation_symbol=sym,
            runtime_producer="AlgorithmSelectionEngine", runtime_consumer="dcm.learning.registry",
            applicability_contract=appl, input_contract="structured features", output_contract="estimate/score",
            semantic_scope=name, fallback_algorithm_id=fb,
        ))
    challengers = [
        ("ALG-ML-TABULAR-003", "Random Forest", "ML_TABULAR", "ALG-ML-TABULAR-001"),
        ("ALG-ML-TABULAR-004", "Extra Trees", "ML_TABULAR", "ALG-ML-TABULAR-001"),
        ("ALG-ML-TABULAR-005", "Histogram Gradient Boosting", "ML_TABULAR", "ALG-ML-TABULAR-001"),
        ("ALG-ML-TABULAR-006", "XGBoost", "ML_TABULAR", "ALG-ML-TABULAR-005"),
        ("ALG-ML-TABULAR-007", "LightGBM", "ML_TABULAR", "ALG-ML-TABULAR-005"),
        ("ALG-ML-TABULAR-008", "CatBoost", "ML_TABULAR", "ALG-ML-TABULAR-005"),
        ("ALG-ML-TABULAR-009", "Generalized Additive Models", "ML_TABULAR", "ALG-ML-TABULAR-002"),
        ("ALG-ML-TABULAR-011", "Quantile Gradient Boosting", "ML_TABULAR", "ALG-ML-TABULAR-010"),
        ("ALG-ML-TABULAR-012", "NGBoost", "ML_TABULAR", "ALG-ML-TABULAR-010"),
        ("ALG-ML-TIME-004", "Kalman Filters", "ML_TIME", "ALG-ML-TIME-001"),
        ("ALG-ML-TIME-005", "Dynamic Linear Models", "ML_TIME", "ALG-ML-TIME-004"),
        ("ALG-ML-TIME-006", "Hidden Markov Models", "ML_TIME", "ALG-ML-TIME-002"),
        ("ALG-ML-TIME-007", "Bayesian Online Change Point Detection", "ML_TIME", "ALG-ML-TIME-003"),
        ("ALG-ML-TIME-008", "PELT", "ML_TIME", "ALG-ML-TIME-002"),
        ("ALG-ML-CAUSAL-001", "Causal Forests", "ML_CAUSAL", "ALG-ML-TABULAR-001"),
        ("ALG-ML-CAUSAL-002", "Double Machine Learning", "ML_CAUSAL", "ALG-ML-TABULAR-001"),
        ("ALG-ML-CAUSAL-003", "Meta-learners S/T/X/R", "ML_CAUSAL", "ALG-ML-TABULAR-001"),
        ("ALG-ML-CAUSAL-004", "TMLE", "ML_CAUSAL", "ALG-ML-TABULAR-001"),
        ("ALG-ML-PROB-002", "Gaussian Processes", "ML_PROB", "ALG-ML-TABULAR-001"),
        ("ALG-ML-PROB-004", "Cox PH", "ML_PROB", "ALG-ML-TABULAR-010"),
        ("ALG-ML-PROB-005", "Accelerated Failure-Time models", "ML_PROB", "ALG-ML-TABULAR-010"),
        ("ALG-ML-PROB-006", "Random Survival Forests", "ML_PROB", "ALG-ML-PROB-004"),
        ("ALG-ML-PROB-007", "Extreme Value Theory (GEV/GPD)", "ML_PROB", "ALG-ML-TABULAR-010"),
        ("ALG-ML-PROB-008", "Distributional Regression", "ML_PROB", "ALG-ML-TABULAR-010"),
        ("ALG-CAL-003", "Beta calibration", "CAL", "ALG-CAL-001"),
        ("ALG-CAL-004", "Bayesian Model Averaging", "CAL", "ALG-CAL-002"),
        ("ALG-CAL-005", "Stacking", "CAL", "ALG-CAL-002"),
        ("ALG-CAL-006", "Blending", "CAL", "ALG-CAL-002"),
        ("ALG-UNCERTAINTY-006", "Local Outlier Factor", "UNCERTAINTY", "ALG-UNCERTAINTY-004"),
        ("ALG-UNCERTAINTY-007", "PCA / robust PCA", "UNCERTAINTY", "ALG-UNCERTAINTY-004"),
        ("ALG-FM-001", "TabFM", "FM", "ALG-ML-TABULAR-001"),
        ("ALG-FM-002", "TabPFN-family", "FM", "ALG-ML-TABULAR-001"),
        ("ALG-FM-003", "TabICL-style models", "FM", "ALG-ML-TABULAR-001"),
        ("ALG-FM-004", "TimesFM-3", "FM", "ALG-ML-TIME-001"),
        ("ALG-FM-005", "Graph Neural Networks", "FM", "ALG-GROUP-003"),
        ("ALG-FM-006", "Graph Attention Networks", "FM", "ALG-GROUP-003"),
        ("ALG-FM-007", "Graph Transformers", "FM", "ALG-GROUP-003"),
        ("ALG-FM-008", "heterogeneous GNNs", "FM", "ALG-GROUP-003"),
        ("ALG-FM-009", "temporal GNNs", "FM", "ALG-ML-TIME-001"),
        ("ALG-FM-010", "hypergraph neural networks", "FM", "ALG-INDEX-014"),
        ("ALG-FM-011", "Normalizing Flows", "FM", "ALG-ML-PROB-001"),
        ("ALG-FM-012", "Neural SDEs", "FM", "ALG-ML-TIME-001"),
        ("ALG-FM-013", "conditional diffusion", "FM", "ALG-ML-PROB-001"),
        ("ALG-FM-014", "mixture density networks", "FM", "ALG-GROUP-018"),
        ("ALG-FM-015", "symbolic regression", "FM", "ALG-ML-TABULAR-001"),
        ("ALG-FM-016", "genetic programming", "FM", "ALG-ML-TABULAR-001"),
        ("ALG-FM-017", "meta-learning", "FM", "ALG-ML-TABULAR-001"),
        ("ALG-FM-018", "self-supervised representation learning", "FM", "ALG-SEARCH-023"),
        ("ALG-FM-019", "contrastive learning", "FM", "ALG-SEARCH-023"),
        ("ALG-FM-020", "causal representation learning", "FM", "ALG-ML-CAUSAL-001"),
        ("ALG-FM-021", "offline reinforcement learning", "FM", "ALG-SCHED-001"),
    ]
    for aid, name, fam, fb in challengers:
        rows.append(_a(
            aid, name, fam, "PERMANENT_CHALLENGER",
            implementation_module="dcm.algorithms.ml_families", implementation_symbol="not_active_challenger",
            runtime_producer="AlgorithmFrontierReview", runtime_consumer="benchmarks/algorithm_frontier",
            applicability_contract=f"permanent challenger family: {name}; not a production ChatGPT dependency",
            input_contract="family-specific", output_contract="challenger score",
            semantic_scope=name, fallback_algorithm_id=fb, portability_class="NOT_PORTABLE_CHALLENGER",
        ))
    return tuple(rows)


ALGORITHM_RECORDS = ALGORITHM_RECORDS + _ml()


def registry_document() -> dict[str, Any]:
    return {
        "schema": SCHEMA,
        "constitutionVersion": CONSTITUTION_VERSION,
        "promptDeclaredConstitutionSha256": "bba7b082bf67e12d87e675ac58d5b6f96d9cbad9b6a487a0aa157bf7cef9e599",
        "algorithms": [dict(row) for row in ALGORITHM_RECORDS],
    }
