"""Stat-type and league identity maps. Unknown labels stay unknown — no nearest match."""

from __future__ import annotations

import re

_STAT = {
    "points": "pts",
    "pts": "pts",
    "rebounds": "reb",
    "reb": "reb",
    "assists": "ast",
    "ast": "ast",
    "pra": "pra",
    "pts rebs asts": "pra",
    "pts reb ast": "pra",
    "points rebounds assists": "pra",
    "pts rebs ast": "pra",
    "pts rebs": "pr",
    "points rebounds": "pr",
    "pts asts": "pa",
    "points assists": "pa",
    "rebs asts": "ra",
    "rebounds assists": "ra",
    "3 pt made": "3pm",
    "3pm": "3pm",
    "threes": "3pm",
    "three pointers made": "3pm",
    "3 pointers made": "3pm",
    "3 pt attempted": "3pa",
    "3pa": "3pa",
    "3pta": "3pa",
    "three pointers attempted": "3pa",
    "2 pt made": "2pm",
    "2pm": "2pm",
    "2 pt att": "2pa",
    "2pa": "2pa",
    "fgm": "fgm",
    "fga": "fga",
    "ft made": "ftm",
    "ftm": "ftm",
    "ft attempted": "fta",
    "fta": "fta",
    "offensive rebounds": "oreb",
    "oreb": "oreb",
    "blocks steals": "blk_stl",
    "blks stls": "blk_stl",
    "qtrs w 3 pts": "qtrs_w_3plus_pts",
    "quarters with 3 pts": "qtrs_w_3plus_pts",
    "steals": "stl",
    "stl": "stl",
    "blocks": "blk",
    "blk": "blk",
    "blocked shots": "blk",
    "turnovers": "tov",
    "tov": "tov",
    "to": "to",
    "passing yards": "pass_yds",
    "pass yds": "pass_yds",
    "pass yards": "pass_yds",
    "rushing yards": "rush_yds",
    "rush yds": "rush_yds",
    "rush yards": "rush_yds",
    "receiving yards": "rec_yds",
    "rec yds": "rec_yds",
    "receptions": "receptions",
    "recs": "receptions",
    "reception": "receptions",
    "passing rushing yards": "pass_rush_yds",
    "pass rush yds": "pass_rush_yds",
    "pass rush yards": "pass_rush_yds",
    "rush rec yds": "rush_rec_yds",
    "rushing receiving yards": "rush_rec_yds",
    "field goals made": "fg_made",
    "fg made": "fg_made",
    "tackles": "def_tackles",
    "def tackles": "def_tackles",
    "hits": "h",
    "h": "h",
    "total bases": "tb",
    "tb": "tb",
    "pitcher strikeouts": "k",
    "strikeouts": "k",
    "ks": "k",
    "k": "k",
    "hits runs rbis": "hits_runs_rbi",
    "hits runs rbi": "hits_runs_rbi",
    "h r rbi": "hits_runs_rbi",
    "hits runs and rbis": "hits_runs_rbi",
    "hitter strikeouts": "k",
    "pitching outs": "pitching_outs",
    "pitches thrown": "pitches_thrown",
    # Exact CFB/NFL aliases. Player Touchdowns = rush_td + rec_td (not pass_td).
    "player touchdowns": "rush_rec_td",
    "player tds": "rush_rec_td",
    "pass tds": "pass_td",
    "passing touchdowns": "pass_td",
    "pass td": "pass_td",
    "pass attempts": "pass_att",
    "passing attempts": "pass_att",
    "pass att": "pass_att",
    "pass completions": "pass_cmp",
    "passing completions": "pass_cmp",
    "completions": "pass_cmp",
    "pass cmp": "pass_cmp",
    "pass comp": "pass_cmp",
    "pass comps": "pass_cmp",
    "passing comp": "pass_cmp",
    "rush attempts": "rush_att",
    "rushing attempts": "rush_att",
    "rush att": "rush_att",
    "rush atts": "rush_att",
    "rushing atts": "rush_att",
    "int": "interceptions",
    "ints": "interceptions",
    "interceptions": "interceptions",
    "rush tds": "rush_td",
    "rushing touchdowns": "rush_td",
    "rec tds": "rec_td",
    "receiving touchdowns": "rec_td",
    "pass rush tds": "pass_rush_td",
    "passing rushing touchdowns": "pass_rush_td",
    "fg attempted": "fg_att",
    "pat made": "xp_made",
    "xp made": "xp_made",
    "extra points made": "xp_made",
    "kicking points": "kicking_pts",
    "kicking pts": "kicking_pts",
    "targets": "targets",
    "fantasy score": "fantasy",
    "pitcher fantasy score": "fantasy",
    "longest reception": "longest_reception",
    "longest rec": "longest_reception",
    "longest rush": "longest_rush",
    "longest completion": "longest_completion",
    "longest pass": "longest_completion",
    "longest passing play": "longest_completion",
    "significant strikes": "sig_strikes",
    "sig strikes": "sig_strikes",
    "sig strikes landed": "sig_strikes",
    "shots": "shots",
    "shots on goal": "sog",
    "sog": "sog",
    "aces": "aces",
    "punches landed": "punches_landed",
    "runs": "runs",
    "strokes": "strokes",
    "kills": "kills",
}

_LABEL = {
    "pts": "Points",
    "reb": "Rebounds",
    "ast": "Assists",
    "pra": "Pts+Reb+Ast",
    "pr": "Pts+Rebs",
    "pa": "Pts+Asts",
    "ra": "Rebs+Asts",
    "3pm": "3-PT Made",
    "3pa": "3-PT Attempted",
    "fgm": "FG Made",
    "fga": "FG Attempted",
    "2pm": "2-PT Made",
    "2pa": "2-PT Attempted",
    "ftm": "FT Made",
    "fta": "FT Attempted",
    "tov": "Turnovers",
    "oreb": "Offensive Rebounds",
    "blk": "Blocks",
    "blk_stl": "Blks+Stls",
    "qtrs_w_3plus_pts": "Qtrs w/3+ Pts",
    "stl": "Steals",
    "pass_yds": "Passing Yards",
    "pass_att": "Pass Attempts",
    "pass_cmp": "Pass Completions",
    "pass_td": "Pass TDs",
    "interceptions": "Interceptions",
    "rush_yds": "Rushing Yards",
    "rush_att": "Rush Attempts",
    "rush_td": "Rush TDs",
    "rec_yds": "Receiving Yards",
    "receptions": "Receptions",
    "rec_td": "Rec TDs",
    "targets": "Targets",
    "pass_rush_yds": "Pass+Rush Yds",
    "rush_rec_yds": "Rush+Rec Yds",
    "rush_rec_td": "Player Touchdowns",
    "pass_rush_td": "Pass+Rush TDs",
    "fg_made": "FG Made",
    "xp_made": "PAT Made",
    "kicking_pts": "Kicking Points",
    "def_tackles": "Tackles",
    "h": "Hits",
    "tb": "Total Bases",
    "k": "Strikeouts",
    "hits_runs_rbi": "Hits+Runs+RBIs",
    "sig_strikes": "Sig. Strikes",
    "shots": "Shots",
    "sog": "Shots on Goal",
    "aces": "Aces",
    "punches_landed": "Punches Landed",
    "runs": "Runs",
    "strokes": "Strokes",
    "kills": "Kills",
}

_LEAGUE = {
    "nba": ("NBA", "basketball"),
    "wnba": ("WNBA", "basketball"),
    "nfl": ("NFL", "gridiron"),
    "nflp": ("NFLP", "gridiron"),
    "nfl preseason": ("NFLP", "gridiron"),
    "ncaaf": ("CFB", "gridiron"),
    "cfb": ("CFB", "gridiron"),
    "ncaa football": ("CFB", "gridiron"),
    "college football": ("CFB", "gridiron"),
    "ncaafb": ("CFB", "gridiron"),
    "cfl": ("CFL", "gridiron"),
    "mlb": ("MLB", "baseball"),
    "kbo": ("KBO", "baseball"),
    "npb": ("NPB", "baseball"),
    "nhl": ("NHL", "hockey"),
    "ufc": ("UFC", "combat"),
    "mma": ("UFC", "combat"),
    "boxing": ("BOXING", "combat"),
    "pga": ("PGA", "golf"),
    "atp": ("ATP", "racket"),
    "wta": ("WTA", "racket"),
    "epl": ("EPL", "soccer"),
    "soccer": ("SOCCER", "soccer"),
    "t20": ("T20", "cricket"),
    "cricket": ("T20", "cricket"),
    "cs2": ("CS2", "esports"),
    "otd": ("OTD", "unknown"),
}

_SPORT_FAMILY = {
    "basketball": "basketball",
    "football": "gridiron",
    "gridiron": "gridiron",
    "baseball": "baseball",
    "hockey": "hockey",
    "mma": "combat",
    "combat": "combat",
    "golf": "golf",
    "tennis": "racket",
    "racket": "racket",
    "soccer": "soccer",
    "cricket": "cricket",
    "esports": "esports",
}


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", s.lower()).strip()


def map_stat(label: str | None) -> tuple[str, str]:
    """Return (market_key, market_label). Unknown keys stay as a slug — fail closed later."""
    if not label:
        return ("unknown", "UNKNOWN")
    key = _STAT.get(_norm(label))
    if key:
        return key, _LABEL.get(key, label)
    slug = _norm(label).replace(" ", "_")
    return slug or "unknown", label


def map_league(name: str | None, sport: str | None = None) -> tuple[str, str]:
    raw = _norm(name or "")
    if raw in _LEAGUE:
        return _LEAGUE[raw]
    sport_fam = _SPORT_FAMILY.get(_norm(sport or ""), "unknown")
    if raw:
        return raw.upper()[:12], sport_fam
    if sport_fam != "unknown":
        return sport_fam.upper(), sport_fam
    return "UNKNOWN", "unknown"


def market_label(market: str, fallback: str = "") -> str:
    return _LABEL.get(market, fallback or market)
